### ISSUE TITLE
Lots of warnings logged

### ISSUE THREAD

**Issue by JFronny** [TheJSHuA/JavaDungeons#24] opened 2020-08-04 13:52 UTC
Having just JavaDungeons `1.2.1` and FAPI `0.16.2 build 385` on loader `0.9.0 build 204` causes a lot of warnings logged. This is not a major problem but a bit inconvenient when trying to find things in the log.
Specifically:
```log
[15:46:58] [Worker-Main-10/ERROR]: Using missing texture, unable to load dungeons:textures/particle/particle/green_flame.png : java.io.FileNotFoundException: dungeons:textures/particle/particle/green_flame.png
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: dungeons:blockstates/dungeons_water.json: java.io.FileNotFoundException: dungeons:blockstates/dungeons_water.json
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/dungeons_water.json' missing model for variant: 'dungeons:dungeons_water#level=0'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/dungeons_water.json' missing model for variant: 'dungeons:dungeons_water#level=5'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/dungeons_water.json' missing model for variant: 'dungeons:dungeons_water#level=6'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/dungeons_water.json' missing model for variant: 'dungeons:dungeons_water#level=7'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/dungeons_water.json' missing model for variant: 'dungeons:dungeons_water#level=8'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/dungeons_water.json' missing model for variant: 'dungeons:dungeons_water#level=1'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/dungeons_water.json' missing model for variant: 'dungeons:dungeons_water#level=2'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/dungeons_water.json' missing model for variant: 'dungeons:dungeons_water#level=3'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/dungeons_water.json' missing model for variant: 'dungeons:dungeons_water#level=4'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/dungeons_water.json' missing model for variant: 'dungeons:dungeons_water#level=15'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/dungeons_water.json' missing model for variant: 'dungeons:dungeons_water#level=14'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/dungeons_water.json' missing model for variant: 'dungeons:dungeons_water#level=9'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/dungeons_water.json' missing model for variant: 'dungeons:dungeons_water#level=11'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/dungeons_water.json' missing model for variant: 'dungeons:dungeons_water#level=10'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/dungeons_water.json' missing model for variant: 'dungeons:dungeons_water#level=13'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/dungeons_water.json' missing model for variant: 'dungeons:dungeons_water#level=12'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: dungeons:blockstates/soggy_swamp_water.json: java.io.FileNotFoundException: dungeons:blockstates/soggy_swamp_water.json
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/soggy_swamp_water.json' missing model for variant: 'dungeons:soggy_swamp_water#level=12'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/soggy_swamp_water.json' missing model for variant: 'dungeons:soggy_swamp_water#level=11'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/soggy_swamp_water.json' missing model for variant: 'dungeons:soggy_swamp_water#level=14'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/soggy_swamp_water.json' missing model for variant: 'dungeons:soggy_swamp_water#level=13'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/soggy_swamp_water.json' missing model for variant: 'dungeons:soggy_swamp_water#level=6'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/soggy_swamp_water.json' missing model for variant: 'dungeons:soggy_swamp_water#level=7'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/soggy_swamp_water.json' missing model for variant: 'dungeons:soggy_swamp_water#level=8'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/soggy_swamp_water.json' missing model for variant: 'dungeons:soggy_swamp_water#level=10'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/soggy_swamp_water.json' missing model for variant: 'dungeons:soggy_swamp_water#level=9'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/soggy_swamp_water.json' missing model for variant: 'dungeons:soggy_swamp_water#level=2'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/soggy_swamp_water.json' missing model for variant: 'dungeons:soggy_swamp_water#level=3'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/soggy_swamp_water.json' missing model for variant: 'dungeons:soggy_swamp_water#level=4'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/soggy_swamp_water.json' missing model for variant: 'dungeons:soggy_swamp_water#level=5'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/soggy_swamp_water.json' missing model for variant: 'dungeons:soggy_swamp_water#level=15'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/soggy_swamp_water.json' missing model for variant: 'dungeons:soggy_swamp_water#level=0'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/soggy_swamp_water.json' missing model for variant: 'dungeons:soggy_swamp_water#level=1'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/tent.json' missing model for variant: 'dungeons:tent#facing=down'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/tent.json' missing model for variant: 'dungeons:tent#facing=up'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/teapot.json' missing model for variant: 'dungeons:teapot#facing=down'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/teapot.json' missing model for variant: 'dungeons:teapot#facing=up'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/chains.json' missing model for variant: 'dungeons:chains#above=true,below=true'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/cw_gravestone.json' missing model for variant: 'dungeons:cw_gravestone#facing=down'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/cw_gravestone.json' missing model for variant: 'dungeons:cw_gravestone#facing=up'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/cw_mossy_gravestone.json' missing model for variant: 'dungeons:cw_mossy_gravestone#facing=down'
[15:47:01] [Worker-Main-9/WARN]: Exception loading blockstate definition: 'dungeons:blockstates/cw_mossy_gravestone.json' missing model for variant: 'dungeons:cw_mossy_gravestone#facing=up'
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:block/creeper_woods/mossy_gravestone
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:block/teapot
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:item/unlit_brazier
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:item/cw_gravestone
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:block/brazier/green_lit
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:block/creeper_woods/glow_mushroom/0
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:block/creeper_woods/gravestone
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:item/ripped_banner
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:item/cw_glow_mushroom
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:block/creeper_woods/glow_mushroom/2
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:block/food_box/fish
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:item/green_lit_brazier
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:block/creeper_woods/glow_mushroom/1
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:block/creeper_woods/pop_flower/0
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:block/creeper_woods/pop_flower/1
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:block/creeper_woods/pop_flower/2
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:block/creeper_woods/pop_flower/3
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:block/food_box/orange
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:block/creeper_woods/flower_patch
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:item/fish_food_box
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:item/teapot
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:item/open_book
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:block/creeper_woods/glow_mushroom/3
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:block/ripped_banner_rotated
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:block/ripped_banner
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:item/corn_food_box
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:item/cw_mossy_gravestone
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:block/water_plant
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:item/closed_book
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:block/brazier/lit
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:block/book/open_0
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:block/book/open_1
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:block/book/open_2
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:block/food_box/corn
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:item/orange_food_box
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:block/book/closed_0
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:block/book/closed_1
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:block/book/closed_2
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:block/tray/yellow_tulip
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:item/apple_food_box
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:block/brazier/unlit
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:block/food_box/apple
[15:47:02] [Worker-Main-9/WARN]: Unable to resolve texture reference: #missing in dungeons:item/lit_brazier
[15:47:02] [Worker-Main-9/WARN]: Texture dungeons:block/coals with size 8x8 limits mip level from 4 to 3
```
(This log is from a fresh MultiMC instance btw)

**Comment by ashie404** [comment] 2020-08-07 19:37
Duplicate of #16 
this has been fixed, but the release with the fix is not out yet (should be out sometime in the near future)

**Closed as completed by ashie404** 2020-08-07 19:37 UTC
